### ISSUE TITLE
Compare only html tags

### ISSUE THREAD

**Issue by LeoCBS** [TeamHG-Memex/extract-html-diff#1]
Hi, 

have one possibility to compare only html structure? without validate html content?

If not, this project have this ambition?

thanks!

**Comment by lopuhin** [comment]
Hi @LeoCBS , no, the idea here is that the base html structure is similar (e.g. two pages are generated using the same template), but the content is different.
Right now the project is very much in flux, but I'm not sure it will ever have this ambition.

**Comment by LeoCBS** [comment]
thanks for you answer @lopuhin 

i am working in some spiders.. and when source (website) have some layout changes.. the parser data break.. and the spider don't produce more data 

if i had some way to detected or monitoring this source changes.. would be nice

do you know some project or way to deal with it?

thanks!

**Comment by lopuhin** [comment]
I see were you are coming from - yes, this is a common problem, but unfortunately I don't know any projects that try to solve it.
